version: '3.7'

services:

#PHP-FPM Service
app:
  build:
    context: . 
    dockerfile: Dockerfile

  container_name: app
  restart: unless-stopped
  tty: true
  working_dir: /var/www

  volumes:
  - ./:/var/www
  - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  network:
  - app-network

  #nginx service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true

    ports
    - "8100:80"
    - "8143:443"

    volumes:
    - ./:/var/www
    - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

    network:
    - app-network

    db:
      imageL mariadb:10.5.6
      container_name:db
      restart: unless-stopped
      tty: true

      ports:
      - "3306:3306"

      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: 123456

      volumes:
        - mariadbdata:/var/lib/mysql
        - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf

      networks:
        - app-network

    #Volmes
    volumes:
      mariadbdata:
        driver: local

    #Networks
    networks:
      app-network:
        driver: bridge